### ISSUE TITLE
豆瓣海报问题

### ISSUE THREAD

**Issue by rachpt** [rachpt/AutoSeed#8]
最近的豆瓣海报图片 要求 `no-referrer-when-downgrade`
而浏览器 默认会使用 referrer，于是海报 403.

下一步，海报使用图床，
还有图床这一块的优化一下， sm.ms 吞图太严重，考虑加入一个图片 api 池，每次随机挑一个。

**Comment by rachpt** [comment]
增加 [m1905 电影网](http://www.1905.com/mdb/film/) 海报，待稳定后 push 至 master。:smile:

**Comment by ZeppLu** [comment]
其实不用图床也行，把域名里的img3换成img1即可

**Comment by rachpt** [comment]
> 其实不用图床也行，把域名里的img3换成img1即可

目前已经加了这个，图床那个是用来上传 缩略图 用的，所有的 poster 都不会主动下载使用图床(byr除外)
https://github.com/rachpt/AutoSeed/blob/af2564fc86e1ae8942b56707f3348fedf1a6ea8b/get_desc/generate.sh#L171
